name: Bug/Crash Report
description: Create a bug or crash report for DiscordColorways.
labels: [bug]
title: "[Bug] <title>"

body:
  - type: markdown
    attributes:
      value: |
        # READ THIS BEFORE OPENING AN ISSUE

        Keep issues either here or on the [official support server](https://discord.gg/67VRpSjzxU). Do not open an issue on one platform and follow it up on another unless you're told so by me or another contributor. Do not open the same issue twice on both the server and here.

        DO NOT OPEN AN ISSUE WITHOUT THE REQUIRED INFO FILLED IN PROPERLY. Don't fill up required fields with random text just to post an issue that ultimately translates to "Doesn't work, pls fix".
        
        Doing any of the above will get:
        * Your issue removed
        * Your GitHub account blocked from making new issues
  
  - type: input
    id: discord
    attributes:
      label: Discord Account
      description: Who on Discord is making this request? Not required but encouraged for easier follow-up
      placeholder: username
    validations:
      required: false

  - type: input
    id: client-mod
    attributes:
      label: Client Mod
      description: What client mod are you using to install DiscordColorways?
      placeholder: BetterDiscord/Vencord
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happens when the bug or crash occurs?
      description: Where does this bug or crash occur, when does it occur, etc.
      placeholder: The bug/crash happens sometimes when I do ..., causing this to not work/the app to crash. I think it happens because of ...
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: What is the expected behaviour?
      description: Simply detail what the expected behaviour is.
      placeholder: I expect Vencord/Discord to open the ... page instead of ..., it prevents me from doing ...
    validations:
      required: true

  - type: textarea
    id: steps-to-take
    attributes:
      label: How do you recreate this bug or crash?
      description: Give us a list of steps in order to recreate the bug or crash.
      placeholder: |
        1. Do ...
        2. Then ...
        3. Do this ..., ... and then ...
        4. Observe "the bug" or "the crash"
    validations:
      required: true

  - type: textarea
    id: crash-log
    attributes:
      label: Errors
      description: Open the Developer Console with Ctrl/Cmd + Shift + i. Then look for any red errors (Ignore network errors like Failed to load resource) and paste them between the "```".
      value: |
        ```
        Replace this text with your crash-log.
        ```
    validations:
      required: false

  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      description: We only accept reports for bugs that happen on Discord Stable. Canary and PTB are Development branches and may be unstable
      options:
        - label: I am using Discord Stable or tried on Stable and this bug happens there as well
          required: true
        - label: I have read the requirements for opening an issue above
          required: true
